services:
  - type: web
    name: gharpayy-crm
    env: python
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate --run-syncdb
      python manage.py create_admin
      python manage.py seed_data
    startCommand: gunicorn gharpayy.wsgi:application --log-file - --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: gharpayy-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: gharpayy
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@gharpayy.com
      - key: ADMIN_PASSWORD
        value: admin123

databases:
  - name: gharpayy-db
    plan: free
    region: oregon
