services:
  - type: web
    name: gharpayy-crm
    env: python
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate --run-syncdb
    startCommand: gunicorn gharpayy.wsgi:application --log-file - --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: gharpayy
